=== aspectran/scany/test/conf/dtd/scany-2.0.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT scany (local?, client?, server?)>

<!ELEMENT schema (#PCDATA)>
<!ELEMENT directory (#PCDATA)>
<!ELEMENT characterEncoding (#PCDATA)>

<!ELEMENT local (schema, directory, characterEncoding?, spooling?)>

<!ELEMENT spooling (directory? | ftp? | jdbc? | jndi?)>

<!ELEMENT ftp (connection, user, directory)>
<!ELEMENT user (id, password)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ATTLIST password
encryption CDATA #IMPLIED
>

<!ELEMENT jdbc (#PCDATA)>
<!ELEMENT jndi (#PCDATA)>

<!ELEMENT client (local? | http? | remote?)>

<!ELEMENT http (characterEncoding?, url, parameters)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT parameters (parameter*)>

<!ELEMENT parameter (#PCDATA)*>
<!ATTLIST typeAlias
name CDATA #REQUIRED
encryption (true, false) #IMPLIED
compressable (true, false) #IMPLIED
>

<!ELEMENT remote (connection, authentificationKey?, message?)>

<!ELEMENT connection (host, timeout)>
<!ELEMENT host (#PCDATA)>
<!ATTLIST host
port CDATA #REQUIRED
>
<!ELEMENT timeout (#PCDATA)>

<!ELEMENT authentificationKey (#PCDATA)>
<!ELEMENT message EMPTY>
<!ATTLIST message
encryption (true, false) #IMPLIED
compressable (true, false) #IMPLIED
>

<!ELEMENT server (remote, optimizing?)>
<!ELEMENT optimizing (#PCDATA)>

=== aspectran/scany/test/conf/scany.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE scany PUBLIC "-//JHLabs.org//DTD scany 1.0//EN"
                           "./dtd/scany-2.0.dtd">

<scany>

	<local>
		<schema></schema>
		<directory></directory>
		<characterEncoding>utf-8</characterEncoding>
		<spooling>
			<directory></directory>
		</spooling>
	</local>

	<client>
		<http>
			<characterEncoding>utf-8</characterEncoding>
			<url>http://</url>
			<message format="json">
				<keysign encryption="none">1234</keysign>
				<body compressable="true"/>
			</message>
		</http>
	</client>

	<server>
		<remote>
			<connection>
				<host port=""/>
				<timeout>2000</timeout>
			</connection>
			<message format="xml">
				<keysign encryption="none">1234</keysign>
				<body compressable="true"/>
			</message>
		</remote>
		<optimizing>
			
		</optimizing>
	</server>

</scany>
